import { prisma } from "../../src/lib/db/prisma";

export async function seedDiscounts() {
  console.log("🎯 Seeding discounts...");

  // Clear existing vouchers first (due to foreign key constraint)
  await prisma.voucher.deleteMany();
  // Then clear existing discounts
  await prisma.discount.deleteMany();

  const now = new Date();
  const twoDaysLater = new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000);
  const fiveDaysLater = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000);
  const thirtyDaysLater = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const sixHoursLater = new Date(now.getTime() + 6 * 60 * 60 * 1000);
  const tenDaysLater = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000);
  const sevenDaysLater = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

  // Get some products for product-specific discounts
  const products = await prisma.product.findMany({
    take: 30,
    where: {
      isSoftDeleted: false,
    },
  });

  const discounts: any[] = [
    // Voucher-based discounts
    {
      name: "Weekend Fresh Produce",
      percentage: 30,
      type: "PERCENTAGE",
      isVoucher: true,
      isWithMinimum: false,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: twoDaysLater,
    },
    {
      name: "Buy 2 Get 1 Any Product",
      type: "QUANTITY",
      isVoucher: true,
      isWithMinimum: false,
      isTiedToProduct: false,
      buyQuantity: 2,
      freeQuantity: 1,
      startsAt: now,
      endsAt: fiveDaysLater,
    },
    {
      name: "Free Delivery on Orders Above 150k",
      amount: 0,
      type: "FIXED_AMOUNT",
      isVoucher: true,
      isWithMinimum: true,
      minimumPrice: 150000,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: thirtyDaysLater,
    },
    {
      name: "Mega Weekend Sale",
      percentage: 25,
      type: "PERCENTAGE",
      isVoucher: true,
      isWithMinimum: false,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: twoDaysLater,
    },
    {
      name: "Fruit Basket Special",
      percentage: 15,
      type: "PERCENTAGE",
      isVoucher: true,
      isWithMinimum: true,
      minimumPrice: 100000,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: sevenDaysLater,
    },
    {
      name: "New Customer Welcome",
      percentage: 20,
      type: "PERCENTAGE",
      isVoucher: true,
      isWithMinimum: false,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: thirtyDaysLater,
    },
    {
      name: "Buy 3 Get 1 Any Product",
      type: "QUANTITY",
      isVoucher: true,
      isWithMinimum: false,
      isTiedToProduct: false,
      buyQuantity: 3,
      freeQuantity: 1,
      startsAt: now,
      endsAt: tenDaysLater,
    },
    {
      name: "Mid-Week Flash Sale",
      percentage: 35,
      type: "PERCENTAGE",
      isVoucher: true,
      isWithMinimum: true,
      minimumPrice: 200000,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: fiveDaysLater,
    },
    {
      name: "Free Delivery for Orders Above 100k",
      amount: 0,
      type: "FIXED_AMOUNT",
      isVoucher: true,
      isWithMinimum: true,
      minimumPrice: 100000,
      isTiedToProduct: false,
      startsAt: now,
      endsAt: thirtyDaysLater,
    },
  ];

  // Add product-specific flash deals
  if (products.length >= 12) {
    discounts.push(
      {
        name: "Flash Deal 22% Off",
        percentage: 22,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[0].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 17% Off",
        percentage: 17,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[1].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 21% Off",
        percentage: 21,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[2].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 19% Off",
        percentage: 19,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[3].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 25% Off",
        percentage: 25,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[4].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 15% Off",
        percentage: 15,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[5].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 20% Off",
        percentage: 20,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[6].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 18% Off",
        percentage: 18,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[7].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 23% Off",
        percentage: 23,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[8].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 16% Off",
        percentage: 16,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[9].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 24% Off",
        percentage: 24,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[10].id,
        startsAt: now,
        endsAt: sixHoursLater,
      },
      {
        name: "Flash Deal 27% Off",
        percentage: 27,
        type: "PERCENTAGE",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[11].id,
        startsAt: now,
        endsAt: sixHoursLater,
      }
    );
  }

  // Add BOGO products
  if (products.length >= 24) {
    discounts.push(
      {
        name: "Buy 1 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[12].id,
        buyQuantity: 1,
        freeQuantity: 1,
        startsAt: now,
        endsAt: fiveDaysLater,
      },
      {
        name: "Buy 1 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[13].id,
        buyQuantity: 1,
        freeQuantity: 1,
        startsAt: now,
        endsAt: fiveDaysLater,
      },
      {
        name: "Buy 1 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[14].id,
        buyQuantity: 1,
        freeQuantity: 1,
        startsAt: now,
        endsAt: fiveDaysLater,
      },
      {
        name: "Buy 1 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[15].id,
        buyQuantity: 1,
        freeQuantity: 1,
        startsAt: now,
        endsAt: fiveDaysLater,
      },
      {
        name: "Buy 2 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[16].id,
        buyQuantity: 2,
        freeQuantity: 1,
        startsAt: now,
        endsAt: tenDaysLater,
      },
      {
        name: "Buy 2 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[17].id,
        buyQuantity: 2,
        freeQuantity: 1,
        startsAt: now,
        endsAt: tenDaysLater,
      },
      {
        name: "Buy 2 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[18].id,
        buyQuantity: 2,
        freeQuantity: 1,
        startsAt: now,
        endsAt: tenDaysLater,
      },
      {
        name: "Buy 2 Get 1 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[19].id,
        buyQuantity: 2,
        freeQuantity: 1,
        startsAt: now,
        endsAt: tenDaysLater,
      },
      {
        name: "Buy 3 Get 2 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[20].id,
        buyQuantity: 3,
        freeQuantity: 2,
        startsAt: now,
        endsAt: sevenDaysLater,
      },
      {
        name: "Buy 3 Get 2 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[21].id,
        buyQuantity: 3,
        freeQuantity: 2,
        startsAt: now,
        endsAt: sevenDaysLater,
      },
      {
        name: "Buy 3 Get 2 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[22].id,
        buyQuantity: 3,
        freeQuantity: 2,
        startsAt: now,
        endsAt: sevenDaysLater,
      },
      {
        name: "Buy 3 Get 2 Free",
        type: "QUANTITY",
        isVoucher: false,
        isWithMinimum: false,
        isTiedToProduct: true,
        productId: products[23].id,
        buyQuantity: 3,
        freeQuantity: 2,
        startsAt: now,
        endsAt: sevenDaysLater,
      }
    );
  }

  for (const discount of discounts) {
    await prisma.discount.create({
      data: discount,
    });
  }

  console.log(`✅ Created ${discounts.length} discounts`);
}
